# Generated by Django 3.2.4 on 2021-07-07 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookform',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='bookform',
            old_name='BookName',
            new_name='bookname',
        ),
        migrations.RenameField(
            model_name='bookform',
            old_name='Genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='bookform',
            old_name='Language',
            new_name='language',
        ),
    ]
