# Generated by Django 3.2.4 on 2021-07-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinfo', '0002_auto_20210707_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookform',
            name='author',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bookform',
            name='bookname',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bookform',
            name='genre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookform',
            name='language',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
